---
# vars/main.yml - Adapter avant de lancer

# VM VirtualBox
vm_name: "SRV-WIN01"
vm_ram_mb: 4096
vm_cpus: 2
vm_disk_gb: 60
vm_os_type: "Windows2022_64"

# ISO Windows Server 2022 fr-fr
windows_iso_path_win: "C:\\Users\\thomz\\Downloads\\SERVER_EVAL_x64FRE_fr-fr.iso"
windows_iso_path_wsl: "/mnt/c/Users/thomz/Downloads/SERVER_EVAL_x64FRE_fr-fr.iso"
image_index: 2  # 2 = Standard Desktop Experience (verifier avec Get-WindowsImage)

# Dossier de travail
work_dir_win: "C:\\AnsibleVM"
work_dir_wsl: "/mnt/c/AnsibleVM"

# Reseau host-only VirtualBox
hostonly_network_name: "vboxnet0"
hostonly_host_ip: "10.15.0.1"
guest_static_ip: "10.15.0.10"
guest_prefix_length: 24

# Windows
computer_name: "SRV-WIN01"
locale: "fr-FR"
timezone: "Romance Standard Time"

# Mots de passe (definis dans vault.yml, ne pas les mettre ici)
admin_password: "{{ vault_admin_password }}"
dsrm_password:  "{{ vault_dsrm_password }}"

# WinRM
winrm_port: 5985
winrm_wait_timeout_seconds: 2700
reboot_wait_seconds: 300
