[control]
localhost ansible_connection=local

# windows : ajoute dynamiquement par 02-wait-winrm.yml (add_host)

# windows_post_ad : connexion avec compte domaine apres reboot AD
[windows_post_ad]
SRV-WIN01-post ansible_host=10.15.0.10

[windows_post_ad:vars]
ansible_user=LMICHEL\Administrateur
ansible_password={{ admin_password }}
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_port=5985
ansible_winrm_scheme=http
